@startuml Gateway


!include ./C4_definitions/C4_Context.puml
!include ./C4_definitions/C4_Container.puml
!include ./C4_definitions/C4_Component.puml

' Set Layout
LAYOUT_TOP_DOWN()


' Define Elements

Person(user, "End User")
Component(arweave, "Arweave Blockweave")
Component(network, "AR.IO Network")

System_Boundary(ar-io, "AR.IO Gateway"){
    Component(core, "AR.IO Core Service")
    Component(envoy, "Envoy Service")
    Component(observer, "Observer Service")

    ContainerDb(chunks, "Chunk data")
    ContainerDb(headers, "Header Data")
    ContainerDb(contiguous, "Contiguous Data")
    ContainerDb(reports, "Observer Reports")
    ContainerDb(index, "Chain and Bundle Index")
}

' Relationships
BiRel(user, envoy, "User sends data, chain, or GraphQL request to Envoy", "HTTPS" )
BiRel(envoy, arweave, "Chain API requests get data directly from the Blockweave", "HTTP")
BiRel(envoy, core, "GraphQL API and Data API requests are forwarded to the core service")


Rel(core, index, "Indexes and stores chain and bundle data")
Rel(core, chunks, "Saves chunked data")
Rel(core, headers, "Saves header data")
Rel(core, contiguous, "Saves contiguous data")

Rel(observer, reports, "saves observer reports")
Rel(observer, network, "Checks the ability of other gateways in the AR.IO Network to resolve ArNS names", "HTTPS")

' Legend
SHOW_LEGEND()

@enduml