@startuml Gateway


!include ./C4_definitions/C4_Context.puml
!include ./C4_definitions/C4_Container.puml
!include ./C4_definitions/C4_Component.puml

' Set Layout
LAYOUT_TOP_DOWN()


' Define Elements

Person(user, "End User")
Component(arweave, "Arweave Blockweave")
Component(network, "AR.IO Network")

System_Boundary(ar-io, "AR.IO Gateway"){
    Component(core, "AR.IO Core Service")
    Component(envoy, "Envoy Service")
    Component(observer, "Observer Service")

    ContainerDb(index, "Chain and Bundle Index", "Chunked, header, and contiguous data and Observer reports")
}

' Relationships
BiRel(user, envoy, "User sends data, chain, or GraphQL request to Envoy", "HTTPS" )
BiRel(envoy, arweave, "Chain API requests get data directly from the Blockweave", "HTTP")
BiRel(envoy, core, "GraphQL API and Data API requests are forwarded to the core service")


Rel(core, index, "Indexes and stores data locally")


Rel(observer, index, "saves observer reports")
Rel(observer, network, "Checks the ability of other gateways in the AR.IO Network to resolve ArNS names", "HTTPS")

' Legend
SHOW_LEGEND()

@enduml