@startuml GraphQL_API


!include ./C4_Context.puml
!include ./C4_Container.puml
!include ./C4_Component.puml

' Layout
LAYOUT_TOP_DOWN()


' Define Elements

Person(user, "End User")
System_Boundary(gateway, "AR.IO Gateway"){ 
    Component(envoy, "Envoy Service")
    Component(core, "Core Service")
    ContainerDb(index, "Indexed data")
    }


' Define Relationships

BiRel(user, envoy, "User makes GraphQL query to AR.IO Gateway.", "HTTPS")
BiRel(envoy, core, "Envoy forwards the query to the core service")
BiRel(core, index, "Core queries Indexed Data")


' Legend
SHOW_LEGEND()
@enduml