global:
  scrape_interval: 15s # 5 minute scrape interval
  evaluation_interval: 1m # Evaluate rules every 1 minute.

scrape_configs:
  - job_name: 'prometheus' # Scrape configuration for Prometheus itself
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node_exporter' # Scrape server stats
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'ar-io-node' # Scrape our node
    metrics_path: '/ar-io/__gateway_metrics'
    static_configs:
      - targets: ['envoy:3000']
