{
 "title": "ao-cu-node",
 "tags": [ "compute-unit" ],
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Request Counts",
   "type": "timeseries",
   "description": "Request counts for dry-run and state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(\n  ao_cu_http_request_duration_seconds_count[5m]\n)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Dry-Run Response Times (p50, p95, p99)",
   "type": "timeseries",
   "description": "Dry-run response times. Ideally, dry-runs evaluate in < 3 seconds.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(\n  0.90,\n  sum by (le) (\n    rate(ao_cu_http_request_duration_seconds_bucket{\n        method=\"POST\",\n        route=\"/dry-run\"\n    }[5m])\n  )\n)",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(\n  0.95,\n  sum by (le) (\n    rate(ao_cu_http_request_duration_seconds_bucket{\n        method=\"POST\",\n        route=\"/dry-run\"\n    }[5m])\n  )\n)",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(\n  0.99,\n  sum by (le) (\n    rate(ao_cu_http_request_duration_seconds_bucket{\n        method=\"POST\",\n        route=\"/dry-run\"\n    }[5m])\n  )\n)",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * rate(ao_cuprocess_cpu_seconds_total[5m])"
    }
   ]
  },
  {
   "title": "Memory Utilization (Resident)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)"
    }
   ]
  }
 ]
}