{
 "title": "ar-io-node queue lengths",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "arweaveClientRequests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"arweaveClientRequests\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "txFetcher",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"txFetcher\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "txImporter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"txImporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "txOffsetImporter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"txOffsetImporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dataContentAttributeImporter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"dataContentAttributeImporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "dataItemIndexer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"dataItemIndexer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ans104DataIndexer",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"ans104DataIndexer\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ans104Unbundler",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"ans104Unbundler\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "bundleDataImporter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"bundleDataImporter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "webhookEmitter",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "queue_length{job=\"ar_io_nodes\", queue_name=\"webhookEmitter\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}