#!/usr/bin/env bash

export START_HEIGHT=0
export STOP_HEIGHT=0

container=$(
  docker run -d \
    -p 4000:4000 \
    -e START_HEIGHT \
    -e STOP_HEIGHT \
    -v $PWD/data/:/app/data \
    $IMAGE_URI
)

sleep 10

echo "127.0.0.2 ardrive.ar-io.localhost" >> /etc/hosts

echo "Verifying that '__unknown__.ar-io.localhost' returns 404..."
status_code="$(curl -s -w "%{http_code}" -o /dev/null http://__unknown__.ar-io.localhost:4000/)"
if [[ "$status_code" != "404" ]]; then
  echo "Unexpected status code: '$status_code'"
  exit 1
fi

echo "Verifying that 'ardrive.ar-io.localhost' returns 200..."
status_code="$(curl -s -w "%{http_code}" -o /dev/null http://ardrive.ar-io.localhost:4000/)"
if [[ "$status_code" != "200" ]]; then
  echo "Unexpected status code: '$status_code'"
  exit 1
fi

echo "Verifying that 'ardrive.ar-io.localhost' X-ArNS-Resolved-ID header..."
if ! curl -s -i http://ardrive.ar-io.localhost:4000/ | grep 'X-ArNS-Resolved-Id'; then
  echo "Missing X-ArNS-Resolved-Id header"
  exit 1
fi

echo "Verifying that 'ardrive.ar-io.localhost' X-ArNS-TTL header..."
if ! curl -s -i http://ardrive.ar-io.localhost:4000/ | grep 'X-ArNS-TTL'; then
  echo "Missing X-ArNS-TTL header"
  exit 1
fi

echo "ArNS test passed!"
docker stop $container
