#!/usr/bin/env bash

start_time=$(date +%s)

export START_HEIGHT=0
export STOP_HEIGHT=0

container=$(
  docker run -d \
    -p 4000:4000 \
    -e START_HEIGHT \
    -e STOP_HEIGHT \
    -v $PWD/data/:/app/data \
    $IMAGE_URI
)

sleep 10

tx="jdcXEvTOkkhSfGTVzHZ4gNZ1nzfK4MrbLKK5IWgOgzY"

status_code="$(curl -s -w "%{http_code}" -o /dev/null http://localhost:4000/raw/$tx)"
if [[ "$status_code" != "200" ]]; then
  echo "Unexpected raw data status code: '$content_length'"
  exit 1
fi

content_length="$(curl -s -i http://localhost:4000/raw/$tx | grep Content-Length | awk '{print $2}' | tr -d '[:space:]')"
if [[ "$content_length" != "7424" ]]; then
  echo "Unexpected raw data content length: '$content_length'"
  exit 1
fi

status_code="$(curl -s -w "%{http_code}" -o /dev/null http://localhost:4000/$tx)"
if [[ "$status_code" != "404" ]]; then
  echo "Unexpected missing manifest index status code: '$status_code'"
  exit 1
fi

status_code="$(curl -s -w "%{http_code}" -o /dev/null http://localhost:4000/$tx/0)"
if [[ "$status_code" != "200" ]]; then
  echo "Unexpected manifest path status code: '$status_code'"
  exit 1
fi

content_length="$(curl -s -i http://localhost:4000/$tx/0 | grep Content-Length | awk '{print $2}' | tr -d '[:space:]')"
if [[ "$content_length" != "130" ]]; then
  echo "Unexpected manifest path content length: '$content_length'"
  exit 1
fi

echo "Data retrieved successfully."
docker stop $container
