#!/usr/bin/env bash

cd /opt/ar-io-node

# cleanup existing files that might conflict on first deploy
shopt -s extglob
rm -rf .!(env)
rm -rf * # okay since data is stored elsewhere

# TODO backup DBs
