#!/usr/bin/env bash

# exit if a command errors
set -e

cd /opt/ar-io-node

# ensure containers are shut down
if [ "$(docker ps -q)" ]; then
  docker-compose down
fi

# cleanup existing files that might conflict on first deploy
shopt -s extglob
rm -rf .!(env) || true
rm -rf * || true # okay since data is stored in /data and /efs
