#!/usr/bin/env bash

while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:3000/ar-io/healthcheck)" != "200" ]]; do
  echo "Waiting for ar-io service to start..."
  sleep 1
done

service_urls=(
  "http://localhost:3000/ar-io/healthcheck"
)

for url in "${service_urls[@]}"
do
  response=$(curl --write-out '%{http_code}' --silent --output /dev/null $url)
  if [[ "$response" != "200" ]]; then
    echo "Error: $url returned $response"
    exit 1
  fi
done
