DROP TABLE IF EXISTS new_data_item_tags;
DROP TABLE IF EXISTS new_data_items;
DROP TABLE IF EXISTS stable_data_item_tags;
DROP TABLE IF EXISTS tag_values;
DROP TABLE IF EXISTS tag_names;
DROP TABLE IF EXISTS stable_data_items;
DROP TABLE IF EXISTS wallets;
DROP TABLE IF EXISTS bundles;
DROP TABLE IF EXISTS bundle_formats;
