name: Build litestream

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'litestream/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Build and push container image
      - name: Log in to the GitHub Container Registry
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image
        if: ${{ github.ref == 'refs/heads/develop' }}
        uses: docker/build-push-action@v5
        with:
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          context: litestream/
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ar-io/ar-io-litestream:latest
            ghcr.io/ar-io/ar-io-litestream:${{ github.sha }}

      # Success notification
      - name: Send Slack success notification
        if: success()
        env:
          SLACK_TITLE: Build succeeded!
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: rtCamp/action-slack-notify@v2

      # Failure notification
      - name: Send Slack failure notification
        if: failure()
        env:
          SLACK_TITLE: Build failed!
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: rtCamp/action-slack-notify@v2
