name: Build core image

on: [workflow_dispatch]

jobs:
  images:
    runs-on: ubuntu-latest

    if: github.ref == 'refs/heads/develop'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push container image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          labels: |
            org.opencontainers.image.revision=${{ github.sha }}
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/ar-io/ar-io-core:latest
            ghcr.io/ar-io/ar-io-core:${{ github.sha }}
