name: deploy-core-image

on:
  workflow_run:
    workflows: ['build-core']
    types: [completed]

jobs:
  ar-io-dev-deployment:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'

    permissions:
      actions: write
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_BUILD_INVOCATION_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Trigger ar-io.dev deployment
        run: |
          aws lambda invoke \
            --function-name ario-dev-deployment-trigger \
            --region ${{ secrets.AWS_REGION }} \
            --cli-binary-format raw-in-base64-out \
            --payload '{"image_sha": "${{ github.event.workflow_run.head_sha }}"}' \
            /dev/null
