name: deploy-core-image

on:
  workflow_run:
    workflows: ['build-core']
    types: [completed]

jobs:
  ar-io-core-deployment:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      (github.event.workflow_run.head_branch == 'develop' ||
       github.event.workflow_run.head_branch == 'main')

    permissions:
      actions: write
      id-token: write
      contents: read

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_BUILD_INVOCATION_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Determine Deployment Target
        id: get_target
        run: |
          if [[ "${{ github.event.workflow_run.head_branch }}" == "main" ]]; then
            echo "TARGET=deploy-ar-io-prod-core" >> $GITHUB_OUTPUT
          else
            echo "TARGET=deploy-ar-io-dev-core" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Deployment
        run: |
          aws lambda invoke \
            --function-name ario-dev-deployment-trigger \
            --region ${{ secrets.AWS_REGION }} \
            --cli-binary-format raw-in-base64-out \
            --payload '{"image_sha": "${{ github.event.workflow_run.head_sha }}", "event_type": "${{ steps.get_target.outputs.TARGET }}"}' \
            /dev/null

      # Failure notification
      - name: Send Slack failure notification
        if: failure()
        env:
          SLACK_TITLE: Core Image Deployment Failed!
          SLACK_COLOR: danger
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        uses: rtCamp/action-slack-notify@v2
